server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

swagger:
  resourcePackage: com.ihorpolataiko.dropwizardauth.resource
  scan: true